name: Build and Push Docker Image to Docker Hub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Read values.json
        id: values
        uses: juliangruber/read-file-action@v1
        with:
          path: ./ACTION_CONFIG/values.json
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pdrodavi/${{ fromJson(steps.values.outputs.content).name }}:${{ fromJson(steps.values.outputs.content).version }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Create Repo in Docker Hub
        run: docker tag pdrodavi/${{ fromJson(steps.values.outputs.content).name }}:${{ fromJson(steps.values.outputs.content).version }} pdrodavi/${{ fromJson(steps.values.outputs.content).name }}:${{ fromJson(steps.values.outputs.content).version }}    
      - name: Publish to Docker Hub
        run: docker push pdrodavi/${{ fromJson(steps.values.outputs.content).name }}:${{ fromJson(steps.values.outputs.content).version }}